apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: todo-backend
        image: nattasitfluk/todo-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME      # ตรงกับ dbName := os.Getenv("DB_NAME")
          value: "todo_db"
        - name: DB_USER      # ตรงกับ dbUser := os.Getenv("DB_USER")
          value: "postgres"
        - name: DB_PASS      # แก้จาก DB_PASSWORD เป็น DB_PASS ให้ตรงกับโค้ด Go!
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password